// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xDI8E2ioWo0gcwHpno35aEqw-eh-AvA',
    appId: '1:858245145787:web:95e15c108fbe350805b59e',
    messagingSenderId: '858245145787',
    projectId: 'federicorandazzo-a5c9b',
    authDomain: 'federicorandazzo-a5c9b.firebaseapp.com',
    storageBucket: 'federicorandazzo-a5c9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtGH9HBuJ9hbGcaRFhu8hD2zItSUsTZWQ',
    appId: '1:858245145787:android:c59247e20060a75405b59e',
    messagingSenderId: '858245145787',
    projectId: 'federicorandazzo-a5c9b',
    storageBucket: 'federicorandazzo-a5c9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLt0_PgXIw_61L9rCtNVhCdzMob_6Vuj4',
    appId: '1:858245145787:ios:13a8e137e7ee6e7105b59e',
    messagingSenderId: '858245145787',
    projectId: 'federicorandazzo-a5c9b',
    storageBucket: 'federicorandazzo-a5c9b.firebasestorage.app',
    iosClientId: '858245145787-fqlif5mmpaalvc0fhcv0ug50ee0t18co.apps.googleusercontent.com',
    iosBundleId: 'com.example.metronomoStandalone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLt0_PgXIw_61L9rCtNVhCdzMob_6Vuj4',
    appId: '1:858245145787:ios:13a8e137e7ee6e7105b59e',
    messagingSenderId: '858245145787',
    projectId: 'federicorandazzo-a5c9b',
    storageBucket: 'federicorandazzo-a5c9b.firebasestorage.app',
    iosClientId: '858245145787-fqlif5mmpaalvc0fhcv0ug50ee0t18co.apps.googleusercontent.com',
    iosBundleId: 'com.example.metronomoStandalone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6xDI8E2ioWo0gcwHpno35aEqw-eh-AvA',
    appId: '1:858245145787:web:74df262f55e19f1e05b59e',
    messagingSenderId: '858245145787',
    projectId: 'federicorandazzo-a5c9b',
    authDomain: 'federicorandazzo-a5c9b.firebaseapp.com',
    storageBucket: 'federicorandazzo-a5c9b.firebasestorage.app',
  );
}
